# Generated by Django 4.1.4 on 2022-12-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('FAILED', 'FAILED')], max_length=15),
        ),
    ]
